spring.application.name=Auth
spring.security.user.name=user
spring.security.user.password=test

# Cambiar nivel global
#logging.level.root=DEBUG

# Cambiar nivel solo para mi paquete
logging.level.com.fdapp=DEBUG

# Mantener Spring en INFO para no llenarme de logs
logging.level.org.springframework=INFO

#JWT
jwt.secret=mi_super_clave_ultrasecreta_123456789
jwt.expiration=3600000