spring.application.name=Auth
spring.security.user.name=user
spring.security.user.password=test

# Cambiar nivel global
#logging.level.root=DEBUG

# Cambiar nivel solo para tu paquete
logging.level.com.fdapp=DEBUG

# Mantener Spring en INFO para no llenarte de logs
logging.level.org.springframework=INFO